"""Generate a downloadable Jupyter notebook reproducing a Bhumi source page.

Builds a notebook programmatically using nbformat. The notebook uses pyia
for data retrieval, astroquery for spectra, and gala for orbit integration.
"""

from __future__ import annotations

from typing import Any

import nbformat
import numpy as np

_NB_VERSION = 4


def _md(source: str) -> nbformat.NotebookNode:
    """Create a Markdown cell."""
    return nbformat.v4.new_markdown_cell(source.strip())


def _code(source: str) -> nbformat.NotebookNode:
    """Create a code cell."""
    return nbformat.v4.new_code_cell(source.strip())


def generate_notebook(
    source_id: int,
    source: dict[str, Any],
    *,
    has_rvs: bool = False,
    has_xp: bool = False,
    has_6d: bool = False,
) -> str:
    """Build a Jupyter notebook for a given Gaia DR3 source.

    Args:
        source_id: The Gaia DR3 source_id.
        source: Enriched source dictionary (from science.compute_derived_quantities).
        has_rvs: Whether the source has an RVS spectrum.
        has_xp: Whether the source has an XP sampled spectrum.
        has_6d: Whether the source has full 6D phase-space info.

    Returns:
        The notebook as a JSON string (.ipynb content).
    """
    cells: list[nbformat.NotebookNode] = []

    # -----------------------------------------------------------------------
    # Title
    # -----------------------------------------------------------------------
    cells.append(
        _md(f"# Gaia DR3 {source_id}\n\nGenerated by [Bhumi](https://bhumi.app).")
    )

    # -----------------------------------------------------------------------
    # Imports
    # -----------------------------------------------------------------------
    imports = [
        "import astropy.coordinates as coord",
        "import astropy.units as u",
        "import matplotlib.pyplot as plt",
        "import numpy as np",
        "from pyia import GaiaData",
    ]
    if has_rvs or has_xp:
        imports.append("from astroquery.gaia import Gaia")
    if has_6d:
        imports.append("import gala.dynamics as gd")
        imports.append("import gala.potential as gp")
    imports.append("")
    imports.append("plt.style.use('dark_background')")
    cells.append(_code("\n".join(imports)))

    # -----------------------------------------------------------------------
    # Data retrieval via pyia
    # -----------------------------------------------------------------------
    cells.append(_md("## Retrieve source data"))
    cells.append(_code(f"g = GaiaData.from_source_id({source_id})\ng.data"))

    # -----------------------------------------------------------------------
    # Astrometry summary
    # -----------------------------------------------------------------------
    cells.append(_md("## Astrometry"))
    cells.append(
        _code(
            'print(f"RA, Dec = {g.ra[0]:.6f}, {g.dec[0]:.6f}")\n'
            'print(f"l, b    = {g.l[0]:.6f}, {g.b[0]:.6f}")\n'
            'print(f"parallax = {g.parallax[0]:.4f}")\n'
            'print(f"distance = {g.distance[0]:.4f}")\n'
            'print(f"pmra     = {g.pmra[0]:.4f}")\n'
            'print(f"pmdec    = {g.pmdec[0]:.4f}")\n'
            "try:\n"
            '    print(f"RV       = {g.radial_velocity[0]:.2f}")\n'
            "except Exception:\n"
            '    print("RV       = (not available)")'
        )
    )

    # -----------------------------------------------------------------------
    # Photometry
    # -----------------------------------------------------------------------
    cells.append(_md("## Photometry"))
    cells.append(
        _code(
            'print(f"G  = {g.phot_g_mean_mag[0]:.3f}")\n'
            'print(f"BP = {g.phot_bp_mean_mag[0]:.3f}")\n'
            'print(f"RP = {g.phot_rp_mean_mag[0]:.3f}")\n'
            'print(f"BP-RP = {g.phot_bp_mean_mag[0] - g.phot_rp_mean_mag[0]:.3f}")'
        )
    )

    # -----------------------------------------------------------------------
    # CMD (nearby stars)
    # -----------------------------------------------------------------------
    cells.append(_md("## Color–Magnitude Diagram"))
    bp_rp_val = None
    abs_g_val = None
    if (
        source.get("phot_bp_mean_mag") is not None
        and source.get("phot_rp_mean_mag") is not None
        and source.get("phot_g_mean_mag") is not None
        and source.get("parallax") is not None
        and source["parallax"] > 0
    ):
        bp_rp_val = source["phot_bp_mean_mag"] - source["phot_rp_mean_mag"]
        distance_pc = 1000.0 / source["parallax"]
        abs_g_val = source["phot_g_mean_mag"] - 5.0 * np.log10(distance_pc / 10.0)

    healpix = source_id >> 43
    cmd_query = f"""\
# Query nearby stars on the CMD from the same HEALPix region
query = \"\"\"
SELECT bp_rp, phot_g_mean_mag + 5 * LOG10(parallax / 100.) AS abs_g
FROM gaiadr3.gaia_source
WHERE source_id BETWEEN {healpix * 2**43} AND {(healpix + 1) * 2**43 - 1}
  AND parallax > 0 AND parallax_over_error > 5
  AND phot_bp_mean_mag IS NOT NULL
  AND phot_rp_mean_mag IS NOT NULL
\"\"\"
job = Gaia.launch_job(query)
cmd = job.get_results()

fig, ax = plt.subplots(figsize=(6, 6))
ax.hist2d(
    cmd["bp_rp"], cmd["abs_g"],
    bins=[np.arange(-1, 5, 0.05), np.arange(-6, 16, 0.1)],
    cmin=1, cmap="Blues",
)"""

    if bp_rp_val is not None and abs_g_val is not None:
        cmd_query += f"""
ax.plot({bp_rp_val:.3f}, {abs_g_val:.3f}, "*", color="gold", ms=12,
        mec="white", mew=0.5, zorder=10, label="This source")
ax.legend()"""

    cmd_query += """
ax.set_xlabel("BP − RP (mag)")
ax.set_ylabel("M$_G$ (mag)")
ax.invert_yaxis()
ax.set_title("Color–Magnitude Diagram")
plt.tight_layout()"""

    # The CMD cell needs astroquery's Gaia, so add the import if not already
    if not (has_rvs or has_xp):
        cells.append(_code("from astroquery.gaia import Gaia\n\n" + cmd_query))
    else:
        cells.append(_code(cmd_query))

    # -----------------------------------------------------------------------
    # RVS Spectrum
    # -----------------------------------------------------------------------
    if has_rvs:
        cells.append(_md("## RVS Spectrum"))
        cells.append(
            _code(
                f"""\
# Retrieve the RVS mean spectrum
rvs_query = \"\"\"
SELECT *
FROM gaiadr3.rvs_mean_spectrum
WHERE source_id = {source_id}
\"\"\"
job = Gaia.launch_job(rvs_query)
rvs = job.get_results()

wavelength = np.arange(846, 870 + 0.01, 0.01)  # nm, 2401 pixels
flux = np.array(rvs["flux"][0])
flux_err = np.array(rvs["flux_error"][0])

fig, ax = plt.subplots(figsize=(10, 4))
ax.fill_between(wavelength, flux - flux_err, flux + flux_err, alpha=0.2)
ax.plot(wavelength, flux, lw=0.8)
ax.set_xlabel("Wavelength (nm)")
ax.set_ylabel("Normalized flux")
ax.set_title("RVS Mean Spectrum")
plt.tight_layout()"""
            )
        )

    # -----------------------------------------------------------------------
    # XP Spectrum
    # -----------------------------------------------------------------------
    if has_xp:
        cells.append(_md("## XP Sampled Spectrum (BP/RP)"))
        cells.append(
            _code(
                f"""\
# Retrieve the XP sampled mean spectrum
xp_query = \"\"\"
SELECT *
FROM gaiadr3.xp_sampled_mean_spectrum
WHERE source_id = {source_id}
\"\"\"
job = Gaia.launch_job(xp_query)
xp = job.get_results()

wavelength = np.array(xp["wavelength"][0])  # nm
flux = np.array(xp["flux"][0])
flux_err = np.array(xp["flux_error"][0])

fig, ax = plt.subplots(figsize=(10, 4))
ax.fill_between(wavelength, flux - flux_err, flux + flux_err, alpha=0.2)
ax.plot(wavelength, flux, lw=0.8)
ax.set_xlabel("Wavelength (nm)")
ax.set_ylabel("Flux")
ax.set_title("XP Sampled Spectrum (BP/RP)")
plt.tight_layout()"""
            )
        )

    # -----------------------------------------------------------------------
    # Galactocentric coords & orbit (6D only)
    # -----------------------------------------------------------------------
    if has_6d:
        cells.append(_md("## Galactocentric Coordinates & Orbit"))
        cells.append(
            _code(
                """\
coord.galactocentric_frame_defaults.set("v4.0")
galcen_frame = coord.Galactocentric()

# Use pyia's skycoord for the coordinate transformation
c = g.skycoord
galcen = c.transform_to(galcen_frame)

print(f"x  = {galcen.x.to(u.kpc):.4f}")
print(f"y  = {galcen.y.to(u.kpc):.4f}")
print(f"z  = {galcen.z.to(u.kpc):.4f}")
print(f"v_x = {galcen.v_x.to(u.km / u.s):.2f}")
print(f"v_y = {galcen.v_y.to(u.km / u.s):.2f}")
print(f"v_z = {galcen.v_z.to(u.km / u.s):.2f}")"""
            )
        )

        cells.append(
            _md("### Orbit integration (8 Gyr backward, MilkyWayPotential v2)")
        )
        cells.append(
            _code(
                """\
potential = gp.MilkyWayPotential(version="v2")
w0 = gd.PhaseSpacePosition(galcen.data)
orbit = potential.integrate_orbit(w0, dt=-0.5 * u.Myr, n_steps=16_000)

# Orbital parameters
print(f"Pericenter:   {orbit.pericenter():.3f}")
print(f"Apocenter:    {orbit.apocenter():.3f}")
print(f"Eccentricity: {orbit.eccentricity():.4f}")
print(f"z_max:        {orbit.zmax():.3f}")"""
            )
        )

        cells.append(
            _code(
                """\
fig, axes = plt.subplots(1, 3, figsize=(14, 4.5), constrained_layout=True)

x = orbit.x.to(u.kpc).value
y = orbit.y.to(u.kpc).value
z = orbit.z.to(u.kpc).value
R = orbit.cylindrical.rho.to(u.kpc).value

axes[0].plot(x, y, lw=0.3, alpha=0.7)
axes[0].plot(x[0], y[0], "*", color="gold", ms=10, mec="white", mew=0.5, zorder=5)
axes[0].set_xlabel("x (kpc)")
axes[0].set_ylabel("y (kpc)")
axes[0].set_aspect("equal")

axes[1].plot(x, z, lw=0.3, alpha=0.7)
axes[1].plot(x[0], z[0], "*", color="gold", ms=10, mec="white", mew=0.5, zorder=5)
axes[1].set_xlabel("x (kpc)")
axes[1].set_ylabel("z (kpc)")
axes[1].set_aspect("equal")

axes[2].plot(R, z, lw=0.3, alpha=0.7)
axes[2].plot(R[0], z[0], "*", color="gold", ms=10, mec="white", mew=0.5, zorder=5)
axes[2].set_xlabel("R (kpc)")
axes[2].set_ylabel("z (kpc)")
axes[2].set_aspect("equal")

fig.suptitle("Galactic Orbit (8 Gyr backward)")"""
            )
        )

    # -----------------------------------------------------------------------
    # Assemble notebook
    # -----------------------------------------------------------------------
    nb = nbformat.v4.new_notebook()
    nb.metadata["kernelspec"] = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }
    nb.cells = cells

    return nbformat.writes(nb)
